# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4 foldmethod=marker
# ----------------------------------------------------------------------------
#  Author: Mubarak Alrashidi (DeaDSouL)
# Package: dsBash
#    Info: Setting up your bash environment
# License: GNU/GPL v3
#     URL: https://github.com/DeaDSouL/dsBash
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# PATH #{{{
# B1FreeArchiver
PATH="/Applications/B1FreeArchiver.app/Contents/MacOS:${PATH}"

# MacPorts
PATH="/opt/local/bin:/opt/local/sbin:${PATH}"

# MySQL (OSX Builtin)
PATH="/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:${PATH}"

PATH="${HOME}/bin:${PATH}"
export PATH
#}}}
# Add color to terminal #{{{
# (this is all commented out as I use Mac Terminal Profiles)
# from http://osxdaily.com/2012/02/21/add-color-to-the-terminal-in-mac-os-x/

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
#}}}
# ----------------------------------------------------------------------------

