# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4 foldmethod=marker filetype=bash
# ----------------------------------------------------------------------------
#  Author: Mubarak Alrashidi (DeaDSouL)
# Package: dsBash
#    Info: Setting up your bash environment
# License: GNU/GPL v3
#     URL: https://gitlab.com/DeaDSouL/dsBash
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# PATH #{{{
for p in "/Applications/B1FreeArchiver.app/Contents/MacOS" \
    "/opt/local/bin" \
    "/opt/local/sbin" \
    "/usr/local/bin" \
    "/usr/local/sbin" \
    "/usr/local/mysql/bin" \
    "$HOME/.local/bin" \
    "$HOME/bin"; do
    if ! [[ "$PATH" =~ "${p}:" ]]; then
        [[ -d "${p}" ]] && PATH="${p}:${PATH}"
    fi
done
export PATH
#}}}
# Add color to terminal #{{{
# (this is all commented out as I use Mac Terminal Profiles)
# from http://osxdaily.com/2012/02/21/add-color-to-the-terminal-in-mac-os-x/

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
#}}}
# ----------------------------------------------------------------------------

